version: "2"

checks:
  method-count:
    config:
      threshold: 25

engines:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          # make it higher so it does not report bullshit like similarity of abstract method and its implementation
          mass_threshold: 55
