language: node_js

node_js:
  - '8'
  - '9'
  - '10'
  - 'node'

services:
  - mongodb
  - mysql

cache:
  directories:
    - 'node_modules'

script:
  - yarn lint
  - ORM_PARALLEL=1 ORM_PORT=3306 yarn coverage

before_install:
  - mysql -u root -e 'CREATE DATABASE mikro_orm_test;'

after_success:
  - yarn coveralls
  - yarn codacy-coverage
