language: node_js

node_js:
  - '8'
  - '9'
  - '10'
  - 'node'

services:
  - mongodb
  - mysql

cache:
  directories:
    - 'node_modules'

script:
  - yarn lint
  - ORM_PARALLEL=1 yarn test

after_success: yarn coveralls
