language: node_js

node_js:
  - '8'
  - '9'
  - '10'
  - 'node'

services:
  - mongodb

cache:
  directories:
    - 'node_modules'

script:
  - yarn run lint
  - ORM_PARALLEL=1 yarn run test

after_success: yarn coveralls
